version: '2'
services:
    db: 
        image: mariadb:10.5.8
        restart: always
        env_file:
            - db-variables.env
        volumes: 
            - rubynotes-mariadb-volume:/var/lib/mysql
        ports:
            - "3307:3306"
    app: 
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
        env_file:
            - .env
        environment:
            RAILS_DB_HOST: db
volumes:
  rubynotes-mariadb-volume:
